export const sampleData = [
    { image: 'https://i.postimg.cc/2694D7Br/IMG-3831.jpg' },
    { image: 'https://i.postimg.cc/BQLCJkgy/Sam-2436.jpg' },
    { image: 'https://i.postimg.cc/SNBfRd1K/Sam-2437.jpg' },
    { image: 'https://i.postimg.cc/3wKp0cX3/Sam-2562.jpg' },
    { image: 'https://i.postimg.cc/sg59hWb4/Sam-2828.jpg' },
    { image: 'https://i.postimg.cc/rybSZgk9/Sam-3277.jpg' },
    { image: 'https://i.postimg.cc/bw0kJh26/Shin2-0065.jpg' },
    { image: 'https://i.postimg.cc/CM6NTSjk/Shin-0003.jpg' },
    { image: 'https://i.postimg.cc/xC1Kh486/Shin-0013.jpg' },
    { image: 'https://i.postimg.cc/k4Jc951F/Sou-0028.jpg' },
    { image: 'https://i.postimg.cc/Zqc8fSb9/Subh-1697.jpg' },
    { image: 'https://i.postimg.cc/XqZ97BwF/Subh-1873.jpg' },
    { image: 'https://i.postimg.cc/yYZ0M96C/Subh-1985.jpg' },
    { image: 'https://i.postimg.cc/yNBhXdH4/Trin-9274.jpg' },
    { image: 'https://i.postimg.cc/QdZchtV9/Trin-9380.jpg' },
    { image: 'https://i.postimg.cc/hvHTJ4rY/Trin-9409.jpg' },
    { image: 'https://i.postimg.cc/mDkH81pq/Trin-9523.jpg' },
];
